package com.rimark.randomizer;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class RandomizerApplication {

	public static void main(String[] args) {
		Base database = new Base("database"," apple\n" +
				" bridge\n" +
				" candle\n" +
				" drift\n" +
				" ember\n" +
				" falcon\n" +
				" gravel\n" +
				" haven\n" +
				" ignite\n" +
				" jungle\n" +
				" kettle\n" +
				" lantern\n" +
				" marble\n" +
				" nestle\n" +
				" orbit\n" +
				" paddle\n" +
				" quartz\n" +
				" riddle\n" +
				" saddle\n" +
				" tangle\n" +
				" umbrella\n" +
				" velvet\n" +
				" wander\n" +
				" xenon\n" +
				" yellow\n" +
				" zigzag\n" +
				" anchor\n" +
				" blaze\n" +
				" copper\n" +
				" dagger\n" +
				" eagle\n" +
				" fable\n" +
				" goblin\n" +
				" harbor\n" +
				" illusion\n" +
				" jacket\n" +
				" kernel\n" +
				" lemon\n" +
				" mirror\n" +
				" noble\n" +
				" ocean\n" +
				" pebble\n" +
				" quiet\n" +
				" ribbon\n" +
				" silver\n" +
				" tunnel\n" +
				" urgent\n" +
				" valley\n" +
				" walnut\n" +
				" xylophone\n" +
				" yogurt\n" +
				" zero\n" +
				" arctic\n" +
				" boulder\n" +
				" crystal\n" +
				" dungeon\n" +
				" eclipse\n" +
				" flicker\n" +
				" granite\n" +
				" hollow\n" +
				" iron\n" +
				" jewel\n" +
				" knuckle\n" +
				" linger\n" +
				" muffin\n" +
				" narrow\n" +
				" orange\n" +
				" pigeon\n" +
				" quiver\n" +
				" rustle\n" +
				" scarlet\n" +
				" timber\n" +
				" urchin\n" +
				" venom\n" +
				" whisper\n" +
				" exile\n" +
				" yonder\n" +
				" zephyr\n" +
				" abbey\n" +
				" blunder\n" +
				" chorus\n" +
				" decoy\n" +
				" eleven\n" +
				" frenzy\n" +
				" glacier\n" +
				" honey\n" +
				" invent\n" +
				" jigsaw\n" +
				" kitten\n" +
				" ladder\n" +
				" meadow\n" +
				" noodle\n" +
				" oyster\n" +
				" planet\n" +
				" quarry\n" +
				" random\n" +
				" simple\n" +
				" timber\n" +
				" unison\n" +
				" violet\n" +
				" weasel\n" +
				" xeric\n" +
				" yarrow\n" +
				" zipper\n" +
				" almond\n" +
				" basket\n" +
				" cactus\n" +
				" danger\n" +
				" effort\n" +
				" finger\n" +
				" garden\n" +
				" handle\n" +
				" insect\n" +
				" jersey\n" +
				" kindle\n" +
				" locket\n" +
				" mango\n" +
				" needle\n" +
				" onion\n" +
				" pencil\n" +
				" quirky\n" +
				" rocket\n" +
				" socket\n" +
				" tackle\n" +
				" unique\n" +
				" vortex\n" +
				" window\n" +
				" xylite\n" +
				" yam\n" +
				" zinnia\n" +
				" arrow\n" +
				" bubble\n" +
				" castle\n" +
				" dollar\n" +
				" elbow\n" +
				" funnel\n" +
				" goblet\n" +
				" hurdle\n" +
				" insole\n" +
				" jockey\n" +
				" kelp\n" +
				" lobby\n" +
				" muzzle\n" +
				" napkin\n" +
				" opaque\n" +
				" pickle\n" +
				" quorum\n" +
				" ripple\n" +
				" sponge\n" +
				" turtle\n" +
				" usher\n" +
				" violet\n" +
				" walrus\n" +
				" xebec\n" +
				" yolk\n" +
				" zenith\n" +
				" alpine\n" +
				" bonfire\n" +
				" clover\n" +
				" denim\n" +
				" errand\n" +
				" fossil\n" +
				" grotto\n" +
				" herald\n" +
				" inland\n" +
				" jumble\n" +
				" kestrel\n" +
				" lagoon\n" +
				" mellow\n" +
				" nuzzle\n" +
				" otter\n" +
				" plunge\n" +
				" quest\n" +
				" ramble\n" +
				" swivel\n" +
				" thatch\n" +
				" uplift\n" +
				" vivid\n" +
				" willow\n" +
				" xylem\n" +
				" yeoman\n" +
				" zircon\n" +
				" amber\n" +
				" buckle\n" +
				" clutter\n" +
				" donkey\n" +
				" envy\n" +
				" fringe\n" +
				" gutter\n" +
				" hippo\n" +
				" invoke\n" +
				" jinx\n" +
				" kale\n" +
				" luster\n" +
				" magnet\n" +
				" notch\n" +
				" outlet\n" +
				" pounce\n" +
				" quench\n" +
				" russet\n" +
				" sultan\n" +
				" thorny\n" +
				" untold\n" +
				" vulture\n" +
				" wombat\n" +
				" xeric\n" +
				" yucca\n" +
				" zebra\n" +
				" anvil\n" +
				" brisk\n" +
				" cobalt\n" +
				" drizzle\n" +
				" envoy\n" +
				" flute\n" +
				" gasp\n" +
				" hymn\n" +
				" inch\n" +
				" jolly\n" +
				" kneel\n" +
				" lance\n" +
				" moose\n" +
				" nymph\n" +
				" oxide\n" +
				" prowl\n" +
				" quill\n" +
				" realm\n" +
				" snare\n" +
				" trinket\n" +
				" unravel\n" +
				" valor\n" +
				" wedge\n" +
				" xanadu\n" +
				" yawn\n" +
				" zealot\n" +
				" acorn\n" +
				" broth\n" +
				" cobble\n" +
				" dwarf\n" +
				" epoch\n" +
				" flap\n" +
				" gaunt\n" +
				" hinge\n" +
				" inlet\n" +
				" jest\n" +
				" knob\n" +
				" latch\n" +
				" mortar\n" +
				" nudge\n" +
				" odor\n" +
				" prism\n" +
				" quota\n" +
				" ramp\n" +
				" snail\n" +
				" tonic\n" +
				" unify\n" +
				" vault\n" +
				" whirl\n" +
				" yacht\n" +
				" zone\n" +
				" acrid\n" +
				" brooch\n" +
				" comet\n" +
				" dusk\n" +
				" erase\n" +
				" flask\n" +
				" glyph\n" +
				" hatch\n" +
				" imply\n" +
				" jut\n" +
				" knave\n" +
				" leech\n" +
				" mirth\n" +
				" niche\n" +
				" omen\n" +
				" prune\n" +
				" rabid\n" +
				" scalp\n" +
				" torso\n" +
				" undo\n" +
				" vague\n" +
				" wrath\n" +
				" yard\n" +
				" zeal\n" +
				" acid\n" +
				" brood\n" +
				" coil\n" +
				" dye\n" +
				" erupt\n" +
				" flaw\n" +
				" gnaw\n" +
				" heave\n" +
				" imp\n" +
				" jade\n" +
				" knit\n" +
				" lunge\n" +
				" myth\n" +
				" nap\n" +
				" ooze\n" +
				" pulse\n" +
				" rage\n" +
				" scald\n" +
				" toss\n" +
				" urge\n" +
				" vast\n" +
				" wield\n" +
				" yearn\n" +
				" zoom\n" +
				" abyss\n" +
				" brawl\n" +
				" coax\n" +
				" deed\n" +
				" evade\n" +
				" fend\n" +
				" groan\n" +
				" haul\n" +
				" idle\n" +
				" jam\n" +
				" knack\n" +
				" lurk\n" +
				" moan\n" +
				" nag\n" +
				" oath\n" +
				" pact\n" +
				" rave\n" +
				" scorn\n" +
				" taunt\n" +
				" usurp\n" +
				" vow\n" +
				" wane\n" +
				" yell\n" +
				" ajar\n" +
				" brawn\n" +
				" cob\n" +
				" deft\n" +
				" even\n" +
				" feud\n" +
				" grim\n" +
				" hawk\n" +
				" ire\n" +
				" jab\n" +
				" kneel\n" +
				" lull\n" +
				" mock\n" +
				" nod\n" +
				" obey\n" +
				" pang\n" +
				" rein\n" +
				" seep\n" +
				" thud\n" +
				" utter\n" +
				" veil\n" +
				" wade\n" +
				" yen\n" +
				" akin\n" +
				" bred\n" +
				" clad\n" +
				" dim\n" +
				" etch\n" +
				" faze\n" +
				" grid\n" +
				" heed\n" +
				" irk\n" +
				" jeer\n" +
				" kneel\n" +
				" lend\n" +
				" meld\n" +
				" numb\n" +
				" owe\n" +
				" pave\n" +
				" rend\n" +
				" shed\n" +
				" tint\n" +
				" upon\n" +
				" vent\n" +
				" wax\n" +
				" yin\n" +
				" aloft\n" +
				" brace\n" +
				" clamp\n" +
				" dense\n" +
				" equip\n" +
				" flair\n" +
				" grasp\n" +
				" hatch\n" +
				" imply\n" +
				" jolt\n" +
				" knit\n" +
				" loft\n" +
				" mold\n" +
				" nip\n" +
				" olive\n" +
				" pelt\n" +
				" roam\n" +
				" shrug\n" +
				" tilt\n" +
				" undue\n" +
				" verge\n" +
				" wary\n" +
				" zest\n" +
				" alley\n" +
				" brand\n" +
				" clank\n" +
				" depot\n" +
				" equate\n" +
				" flint\n" +
				" graze\n" +
				" haze\n" +
				" impart\n" +
				" jounce\n" +
				" kneel\n" +
				" lodge\n" +
				" molt\n" +
				" nook\n" +
				" onset\n" +
				" perch\n" +
				" roost\n" +
				" shun\n" +
				" tinge\n" +
				" unwrap\n" +
				" vetch\n" +
				" waver\n" +
				" zing\n" +
				" aloe\n" +
				" breach\n" +
				" clash\n" +
				" depth\n" +
				" equip\n" +
				" flock\n" +
				" grief\n" +
				" heap\n" +
				" impact\n" +
				" joust\n" +
				" knock\n" +
				" lore\n" +
				" monk\n" +
				" norm\n" +
				" optic\n" +
				" peril\n" +
				" rout\n" +
				" siege\n" +
				" torque\n" +
				" upend\n" +
				" vigor\n" +
				" wilt\n" +
				" zinc\n" +
				" amble\n" +
				" brink\n" +
				" cleft\n" +
				" derby\n" +
				" eject\n" +
				" floss\n" +
				" grill\n" +
				" hemp\n" +
				" infer\n" +
				" jumbo\n" +
				" knoll\n" +
				" lure\n" +
				" muse\n" +
				" notch\n" +
				" orca\n" +
				" perk\n" +
				" royal\n" +
				" skew\n" +
				" topple\n" +
				" usher\n" +
				" virile\n" +
				" winch\n" +
				" yore\n" +
				" amend\n" +
				" brisk\n" +
				" click\n" +
				" desk\n" +
				" elate\n" +
				" foam\n" +
				" grind\n" +
				" herb\n" +
				" ingot\n" +
				" junk\n" +
				" koala\n" +
				" lyric\n" +
				" mute\n" +
				" novice\n" +
				" orbit\n" +
				" petty\n" +
				" runoff\n" +
				" skiff\n" +
				" torch\n" +
				" untie\n" +
				" vista\n" +
				" wince\n" +
				" yoke\n" +
				" amiss\n" +
				" brittle\n" +
				" clinch\n" +
				" devise\n" +
				" elect\n" +
				" foray\n" +
				" gripe\n" +
				" heron\n" +
				" ingest\n" +
				" karma\n" +
				" lance\n" +
				" knack\n" +
				" mango\n" +
				" novel\n" +
				" osprey\n" +
				" pewter\n" +
				" ruse\n" +
				" skunk\n" +
				" torment\n" +
				" upbeat\n" +
				" vivid\n" +
				" witty\n" +
				" yogi\n" +
				" ample\n" +
				" bronze\n" +
				" clone\n" +
				" devour\n" +
				" elude\n" +
				" forgo\n" +
				" grit\n" +
				" hew\n" +
				" inject\n" +
				" keen\n" +
				" lard\n" +
				" manor\n" +
				" oblong\n" +
				" pawn\n" +
				" rust\n" +
				" slant\n" +
				" touch\n" +
				" urban\n" +
				" void\n" +
				" wren\n" +
				" zany\n" +
				" ankle\n" +
				" brood\n" +
				" clove\n" +
				" dial\n" +
				" ember\n" +
				" fort\n" +
				" grove\n" +
				" hike\n" +
				" inner\n" +
				" keep\n" +
				" laser\n" +
				" maple\n" +
				" oboe\n" +
				" peak\n" +
				" rye\n" +
				" sleek\n" +
				" tow\n" +
				" upset\n" +
				" vole\n" +
				" wring\n" +
				" yak\n" +
				" annex\n" +
				" brook\n" +
				" club\n" +
				" dig\n" +
				" emit\n" +
				" foul\n" +
				" growl\n" +
				" hill\n" +
				" insist\n" +
				" key\n" +
				" last\n" +
				" marsh\n" +
				" occur\n" +
				" peach\n" +
				" sack\n" +
				" slope\n" +
				" trace\n" +
				" used\n" +
				" volt\n" +
				" wrote\n" +
				" yap\n" +
				" apart\n" +
				" bruise\n" +
				" coast\n" +
				" digit\n" +
				" encode\n" +
				" found\n" +
				" guard\n" +
				" hint\n" +
				" intent\n" +
				" kink\n" +
				" laugh\n" +
				" match\n" +
				" offer\n" +
				" pearl\n" +
				" safe\n" +
				" small\n" +
				" trade\n" +
				" usual\n" +
				" vote\n" +
				" wrote\n" +
				" yard\n" +
				" apart\n" +
				" brush\n" +
				" coin\n" +
				" dine\n" +
				" end\n" +
				" frame\n" +
				" guess\n" +
				" hold\n" +
				" iron\n" +
				" kind\n" +
				" leaf\n" +
				" metal\n" +
				" open\n" +
				" pile\n" +
				" salt\n" +
				" smart\n" +
				" trail\n" +
				" user\n" +
				" woke\n" +
				" yarn\n" +
				" ape\n" +
				" build\n" +
				" cold\n" +
				" dip\n" +
				" enjoy\n" +
				" free\n" +
				" hand\n" +
				" hook\n" +
				" item\n" +
				" kiss\n" +
				" lean\n" +
				" mind\n" +
				" outside\n" +
				" pipe\n" +
				" same\n" +
				" snap\n" +
				" trap\n" +
				" used\n" +
				" wood\n" +
				" zero\n" +
				" area\n" +
				" burn\n" +
				" come\n" +
				" disk\n" +
				" equal\n" +
				" fresh\n" +
				" hang\n" +
				" hope\n" +
				" into\n" +
				" know\n" +
				" left\n" +
				" mode\n" +
				" over\n" +
				" plan\n" +
				" save\n" +
				" soil\n" +
				" tree\n" +
				" upon\n" +
				" word\n" +
				" zone\n" +
				" army\n" +
				" busy\n" +
				" core\n" +
				" draw\n" +
				" error\n" +
				" front\n" +
				" hard\n" +
				" horse\n" +
				" invite\n" +
				" last\n" +
				" light\n" +
				" more\n" +
				" own\n" +
				" point\n" +
				" seat\n" +
				" some\n" +
				" trip\n" +
				" used\n" +
				" work\n" +
				" zoom\n" +
				" base\n" +
				" call\n" +
				" cost\n" +
				" drop\n" +
				" even\n" +
				" full\n" +
				" harm\n" +
				" hour\n" +
				" join\n" +
				" late\n" +
				" line\n" +
				" move\n" +
				" page\n" +
				" print\n" +
				" sell\n" +
				" soon\n" +
				" true\n" +
				" up\n" +
				" way\n" +
				" aid\n" +
				" ball\n" +
				" calm\n" +
				" deep\n" +
				" exit\n" +
				" face\n" +
				" gain\n" +
				" have\n" +
				" hurl\n" +
				" jail\n" +
				" land\n" +
				" link\n" +
				" name\n" +
				" pack\n" +
				" push\n" +
				" send\n" +
				" spin\n" +
				" turn\n" +
				" use\n" +
				" win\n" +
				" add\n" +
				" bank\n" +
				" card\n" +
				" deal\n" +
				" edge\n" +
				" fact\n" +
				" game\n" +
				" hear\n" +
				" hurt\n" +
				" jump\n" +
				" large\n" +
				" list\n" +
				" near\n" +
				" part\n" +
				" put\n" +
				" set\n" +
				" spot\n" +
				" test\n" +
				" use\n" +
				" win\n" +
				" ace\n" +
				" bare\n" +
				" care\n" +
				" door\n" +
				" ease\n" +
				" fair\n" +
				" give\n" +
				" heat\n" +
				" idea\n" +
				" just\n" +
				" less\n" +
				" load\n" +
				" need\n" +
				" pass\n" +
				" quit\n" +
				" show\n" +
				" stay\n" +
				" tell\n" +
				" view\n" +
				" wide\n" +
				" aim\n" +
				" base\n" +
				" case\n" +
				" done\n" +
				" each\n" +
				" fall\n" +
				" good\n" +
				" help\n" +
				" huge\n" +
				" kind\n" +
				" live\n" +
				" long\n" +
				" next\n" +
				" pay\n" +
				" rate\n" +
				" side\n" +
				" stop\n" +
				" term\n" +
				" wait\n" +
				" wish\n" +
				" age\n" +
				" best\n" +
				" city\n" +
				" down\n" +
				" else\n" +
				" fill\n" +
				" grew\n" +
				" high\n" +
				" hit\n" +
				" keep\n" +
				" lost\n" +
				" look\n" +
				" new\n" +
				" play\n" +
				" read\n" +
				" sign\n" +
				" such\n" +
				" then\n" +
				" walk\n" +
				" year\n" +
				" ago\n" +
				" best\n" +
				" also\n" +
				" each\n" +
				" end\n" +
				" find\n" +
				" got\n" +
				" him\n" +
				" its\n" +
				" knew\n" +
				" lot\n" +
				" low\n" +
				" off\n" +
				" old\n" +
				" ran\n" +
				" run\n" +
				" saw\n" +
				" say\n" +
				" she\n" +
				" sit\n" +
				" six\n" +
				" sky\n" +
				" sun\n" +
				" ten\n" +
				" top\n" +
				" two\n" +
				" war\n" +
				" was\n" +
				" wet\n" +
				" who\n" +
				" why\n" +
				" won\n" +
				" yet\n" +
				" awe\n" +
				" bay\n" +
				" bet\n" +
				" bid\n" +
				" bit\n" +
				" box\n" +
				" boy\n" +
				" bus\n" +
				" but\n" +
				" buy\n" +
				" cap\n" +
				" cat\n" +
				" cue\n" +
				" cup\n" +
				" cut\n" +
				" dad\n" +
				" day\n" +
				" did\n" +
				" die\n" +
				" dog\n" +
				" dot\n" +
				" dug\n" +
				" eat\n" +
				" ego\n" +
				" elm\n" +
				" era\n" +
				" eve\n" +
				" eye\n" +
				" fed\n" +
				" few\n" +
				" fig\n" +
				" fit\n" +
				" fix\n" +
				" fly\n" +
				" fog\n" +
				" for\n" +
				" fox\n" +
				" fun\n" +
				" fur\n" +
				" gap\n" +
				" gas\n" +
				" gel\n" +
				" gem\n" +
				" get\n" +
				" gin\n" +
				" god\n" +
				" gum\n" +
				" gut\n" +
				" guy\n" +
				" gym\n" +
				" hay\n" +
				" hen\n" +
				" her\n" +
				" hid\n" +
				" hip\n" +
				" his\n" +
				" hog\n" +
				" hop\n" +
				" how\n" +
				" hub\n" +
				" hug\n" +
				" ice\n" +
				" ill\n" +
				" ink\n" +
				" inn\n" +
				" ion\n" +
				" ivy\n" +
				" jar\n" +
				" jaw\n" +
				" joy\n" +
				" jug\n" +
				" jut\n" +
				" keg\n" +
				" key\n" +
				" kid\n" +
				" kit\n" +
				" lab\n" +
				" lag\n" +
				" lap\n" +
				" law\n" +
				" lay\n" +
				" leg\n" +
				" let\n" +
				" lid\n" +
				" lip\n" +
				" lit\n" +
				" log\n" +
				" lot\n" +
				" low\n" +
				" lug\n" +
				" mad\n" +
				" man\n" +
				" map\n" +
				" mat\n" +
				" may\n" +
				" mob\n" +
				" mop\n" +
				" mud\n" +
				" mug\n" +
				" nap\n" +
				" net\n" +
				" new\n" +
				" nil\n" +
				" nor\n" +
				" not\n" +
				" nun\n" +
				" nut\n" +
				" oak\n" +
				" odd\n" +
				" oil\n" +
				" opt\n" +
				" orb\n" +
				" ore\n" +
				" our\n" +
				" out\n" +
				" owe\n" +
				" owl\n" +
				" own\n" +
				" pad\n" +
				" pan\n" +
				" pap\n" +
				" par\n" +
				" pat\n" +
				" pay\n" +
				" pea\n" +
				" peg\n" +
				" pen\n" +
				" pet\n" +
				" pie\n" +
				" pig\n" +
				" pin\n" +
				" pit\n" +
				" ply\n" +
				" pod\n" +
				" pop\n" +
				" pot\n" +
				" pry\n" +
				" pub\n" +
				" pun\n" +
				" pup\n" +
				" ram\n" +
				" rap\n" +
				" rat\n" +
				" raw\n" +
				" ray\n" +
				" red\n" +
				" ref\n" +
				" rep\n" +
				" rib\n" +
				" rid\n" +
				" rig\n" +
				" rip\n" +
				" rob\n" +
				" rod\n" +
				" rot\n" +
				" row\n" +
				" rub\n" +
				" rug\n" +
				" rum\n" +
				" sag\n" +
				" sap\n" +
				" sat\n" +
				" sea\n" +
				" shy\n" +
				" sin\n" +
				" sip\n" +
				" sir\n" +
				" slid\n" +
				" sly\n" +
				" sob\n" +
				" sod\n" +
				" son\n" +
				" sow\n" +
				" soy\n" +
				" spa\n" +
				" spy\n" +
				" sty\n" +
				" sub\n" +
				" sum\n" +
				" sup\n" +
				" tab\n" +
				" tag\n" +
				" tan\n" +
				" tap\n" +
				" tar\n" +
				" tax\n" +
				" tea\n" +
				" the\n" +
				" tie\n" +
				" tin\n" +
				" tip\n" +
				" toe\n" +
				" tom\n" +
				" ton\n" +
				" too\n" +
				" tot\n" +
				" toy\n" +
				" try\n" +
				" tub\n" +
				" tug\n" +
				" tux\n" +
				" urn\n" +
				" van\n" +
				" vat\n" +
				" vet\n" +
				" via\n" +
				" vim\n" +
				" vow\n" +
				" wad\n" +
				" wan\n" +
				" war\n" +
				" web\n" +
				" wed\n" +
				" wit\n" +
				" woe\n" +
				" wok\n" +
				" won\n" +
				" woo\n" +
				" wow\n" +
				" yam\n" +
				" yap\n" +
				" yew\n" +
				" yon\n" +
				" zap\n" +
				" zit\n" +
				" zoo\n" +
				" abate\n" +
				" abbey\n" +
				" abbot\n" +
				" abhor\n" +
				" abide\n" +
				" abjure\n" +
				" ablaze\n" +
				" abloom\n" +
				" abode\n" +
				" abolish\n" +
				" abrupt\n" +
				" absence\n" +
				" absorb\n" +
				" abstain\n" +
				" absurd\n" +
				" accent\n" +
				" access\n" +
				" accord\n" +
				" accuse\n" +
				" achieve\n" +
				" acquire\n" +
				" across\n" +
				" active\n" +
				" actual\n" +
				" adapt\n" +
				" adhere\n" +
				" adjust\n" +
				" admire\n" +
				" adopt\n" +
				" adore\n" +
				" adult\n" +
				" advent\n" +
				" advice\n" +
				" affirm\n" +
				" afford\n" +
				" afraid\n" +
				" agenda\n" +
				" agile\n" +
				" agree\n" +
				" ahead\n" +
				" alarm\n" +
				" albeit\n" +
				" album\n" +
				" alert\n" +
				" align\n" +
				" allot\n" +
				" allow\n" +
				" alone\n" +
				" along\n" +
				" aloof\n" +
				" alter\n" +
				" amaze\n" +
				" among\n" +
				" ample\n" +
				" angel\n" +
				" anger\n" +
				" angle\n" +
				" annoy\n" +
				" apathy\n" +
				" apex\n" +
				" apology\n" +
				" appeal\n" +
				" apply\n" +
				" apron\n" +
				" aptly\n" +
				" ardor\n" +
				" argue\n" +
				" arise\n" +
				" array\n" +
				" arson\n" +
				" artsy\n" +
				" ascend\n" +
				" ashamed\n" +
				" assist\n" +
				" assume\n" +
				" assure\n" +
				" atlas\n" +
				" atone\n" +
				" atop\n" +
				" attic\n" +
				" audit\n" +
				" augment\n" +
				" avail\n" +
				" avoid\n" +
				" awake\n" +
				" aware\n" +
				" awful\n" +
				" awhile\n" +
				" badge\n" +
				" baffle\n" +
				" banish\n" +
				" basic\n" +
				" batch\n" +
				" beach\n" +
				" beard\n" +
				" beast\n" +
				" beget\n" +
				" begin\n" +
				" beige\n" +
				" being\n" +
				" below\n" +
				" bench\n" +
				" berth\n" +
				" beseech\n" +
				" bestow\n" +
				" bewail\n" +
				" beware\n" +
				" bewitch\n" +
				" biased\n" +
				" bicker\n" +
				" bitter\n" +
				" blame\n" +
				" blend\n" +
				" blind\n" +
				" blink\n" +
				" bliss\n" +
				" bloat\n" +
				" block\n" +
				" bloom\n" +
				" blot\n" +
				" blunt\n" +
				" blush\n" +
				" boggle\n" +
				" boil\n" +
				" bold\n" +
				" boon\n" +
				" boost\n" +
				" botch\n" +
				" bounce\n" +
				" brace\n" +
				" braid\n" +
				" brake\n" +
				" brave\n" +
				" braze\n" +
				" break\n" +
				" bream\n" +
				" breed\n" +
				" bribe\n" +
				" brief\n" +
				" brine\n" +
				" brisk\n" +
				" broil\n" +
				" broke\n" +
				" brood\n" +
				" brute\n" +
				" budge\n" +
				" bulge\n" +
				" bungle\n" +
				" cache\n" +
				" camel\n" +
				" caped\n" +
				" carry\n" +
				" cause\n" +
				" cease\n" +
				" chain\n" +
				" chalk\n" +
				" chant\n" +
				" charm\n" +
				" chase\n" +
				" cheap\n" +
				" cheat\n" +
				" check\n" +
				" cheek\n" +
				" chess\n" +
				" chest\n" +
				" chew\n" +
				" chief\n" +
				" child\n" +
				" chill\n" +
				" churn\n" +
				" claim\n" +
				" clap\n" +
				" class\n" +
				" clean\n" +
				" clear\n" +
				" clerk\n" +
				" cliff\n" +
				" climb\n" +
				" cling\n" +
				" clog\n" +
				" close\n" +
				" cloud\n" +
				" clown\n" +
				" clue\n" +
				" coach\n" +
				" coerce\n" +
				" coil\n" +
				" collect\n" +
				" color\n" +
				" combine\n" +
				" come\n" +
				" comet\n" +
				" comfort\n" +
				" commit\n" +
				" compact\n" +
				" compare\n" +
				" compel\n" +
				" comply\n" +
				" conceal\n" +
				" concept\n" +
				" concur\n" +
				" condone\n" +
				" confess\n" +
				" confirm\n" +
				" confuse\n" +
				" connect\n" +
				" consist\n" +
				" consult\n" +
				" contact\n" +
				" convey\n" +
				" copied\n" +
				" correct\n" +
				" corrupt\n" +
				" costly\n" +
				" counsel\n" +
				" couple\n" +
				" create\n" +
				" credit\n" +
				" crouch\n" +
				" crowded\n" +
				" cruise\n" +
				" crumble\n" +
				" crunch\n" +
				" crush\n" +
				" daily\n" +
				" damage\n" +
				" dampen\n" +
				" darken\n" +
				" dazzle\n" +
				" deface\n" +
				" defeat\n" +
				" defend\n" +
				" define\n" +
				" delay\n" +
				" delete\n" +
				" deliver\n" +
				" demand\n" +
				" denote\n" +
				" depart\n" +
				" deploy\n" +
				" derive\n" +
				" descend\n" +
				" detect\n" +
				" devote\n" +
				" differ\n" +
				" direct\n" +
				" dismiss\n" +
				" dispel\n" +
				" divide\n" +
				" double\n" +
				" douse\n" +
				" driven\n" +
				" droop\n" +
				" drown\n" +
				" drudge\n" +
				" durable\n" +
				" during\n" +
				" dwelt\n" +
				" eager\n" +
				" easily\n" +
				" effort\n" +
				" elapse\n" +
				" enable\n" +
				" expand\n" +
				" expose\n" +
				" extend\n" +
				" faint\n" +
				" fasten\n" +
				" ferret\n" +
				" fierce\n" +
				" figure\n" +
				" filter\n" +
				" finish\n" +
				" follow\n" +
				" forbid\n" +
				" forest\n" +
				" forgive\n" +
				" formal\n" +
				" foster\n" +
				" gather\n" +
				" gentle\n" +
				" glance\n" +
				" gleam\n" +
				" glide\n" +
				" glimpse\n" +
				" glint\n" +
				" glory\n" +
				" glower\n" +
				" govern\n" +
				" grace\n" +
				" grant\n" +
				" grapple\n" +
				" greet\n" +
				" groom\n" +
				" group\n" +
				" guide\n" +
				" haggle\n" +
				" harness\n" +
				" hasten\n" +
				" hinder\n" +
				" hollow\n" +
				" honest\n" +
				" ignite\n" +
				" ignore\n" +
				" imitate\n" +
				" impose\n" +
				" inspire\n" +
				" intake\n" +
				" intend\n" +
				" involve\n" +
				" isolate\n" +
				" kindle\n" +
				" lavish\n" +
				" lenient\n" +
				" limit\n" +
				" listen\n" +
				" lively\n" +
				" locate\n" +
				" loosen\n" +
				" manage\n" +
				" marvel\n" +
				" master\n" +
				" matter\n" +
				" mingle\n" +
				" mirror\n" +
				" misplace\n" +
				" modest\n" +
				" monitor\n" +
				" mumble\n" +
				" muster\n" +
				" narrow\n" +
				" notice\n" +
				" nourish\n" +
				" obtain\n" +
				" offend\n" +
				" oppose\n" +
				" ordain\n" +
				" outrun\n" +
				" overcome\n" +
				" overlook\n" +
				" pardon\n" +
				" pause\n" +
				" perceive\n" +
				" permit\n" +
				" persist\n" +
				" ponder\n" +
				" prefer\n" +
				" present\n" +
				" prevent\n" +
				" proceed\n" +
				" produce\n" +
				" promise\n" +
				" protect\n" +
				" prove\n" +
				" provide\n" +
				" pursue\n" +
				" rebuild\n" +
				" recall\n" +
				" recite\n" +
				" reduce\n" +
				" refine\n" +
				" reform\n" +
				" refuse\n" +
				" regard\n" +
				" relate\n" +
				" release\n" +
				" remain\n" +
				" remove\n" +
				" repair\n" +
				" repeat\n" +
				" replace\n" +
				" rescue\n" +
				" resist\n" +
				" resolve\n" +
				" restore\n" +
				" return\n" +
				" reveal\n" +
				" reward\n" +
				" rinse\n" +
				" rotate\n" +
				" safeguard\n" +
				" sample\n" +
				" scatter\n" +
				" scrape\n" +
				" search\n" +
				" select\n" +
				" signal\n" +
				" soothe\n" +
				" squash\n" +
				" stride\n" +
				" strive\n" +
				" struggle\n" +
				" submit\n" +
				" suggest\n" +
				" supply\n" +
				" support\n" +
				" suppose\n" +
				" surpass\n" +
				" survive\n" +
				" sustain\n" +
				" tighten\n" +
				" tolerate\n" +
				" transfer\n" +
				" transform\n" +
				" travel\n" +
				" trigger\n" +
				" uncover\n" +
				" understand\n" +
				" unite\n" +
				" unload\n" +
				" verify\n" +
				" welcome\n" +
				" witness\n" +
				" wonder\n" +
				" achieve\n" +
				" benefit\n" +
				" control\n" +
				" enforce\n" +
				" enhance\n" +
				" improve\n" +
				" include\n" +
				" inspire\n" +
				" involve\n" +
				" justify\n" +
				" maintain\n" +
				" minimize\n" +
				" motivate\n" +
				" observe\n" +
				" optimize\n" +
				" organize\n" +
				" perfect\n" +
				" perform\n" +
				" preserve\n" +
				" publish\n" +
				" question\n" +
				" realize\n" +
				" recognize\n" +
				" recommend\n" +
				" reduce\n" +
				" reflect\n" +
				" reinforce\n" +
				" research\n" +
				" share\n" +
				" simplify\n" +
				" snowflake\n" +
				" starlight\n" +
				" rainfall\n" +
				" thunderstorm\n" +
				" lighthouse\n" +
				" riverbank\n" +
				" hilltop\n" +
				" cobblestone\n" +
				" sunbeam\n" +
				" moonrise\n" +
				" campfire\n" +
				" midnight\n" +
				" cliffside\n" +
				" meadowlark\n" +
				" pinecone\n" +
				" sandcastle\n" +
				" seashell\n" +
				" starfish\n" +
				" tideway\n" +
				" driftwood\n" +
				" birchwood\n" +
				" tidepool\n" +
				" foxhole\n" +
				" cornfield\n" +
				" sunflower\n" +
				" buttercup\n" +
				" bluegrass\n" +
				" wildfire\n" +
				" honeybee\n" +
				" ladybug\n" +
				" firefly\n" +
				" grassland\n" +
				" bluebell\n" +
				" snowdrift\n" +
				" iceberg\n" +
				" penguin\n" +
				" reindeer\n" +
				" frostbite\n" +
				" tundra\n" +
				" glacier\n" +
				" avalanche\n" +
				" blizzard\n" +
				" windstorm\n" +
				" hailstorm\n" +
				" monsoon\n" +
				" cyclone\n" +
				" raindrop\n" +
				" dewdrop\n" +
				" foghorn\n" +
				" whirlpool\n" +
				" waterfall\n" +
				" lagoon\n" +
				" swampland\n" +
				" estuary\n" +
				" archipelago\n" +
				" peninsula\n" +
				" continent\n" +
				" ravine\n" +
				" plateau\n" +
				" canyon\n" +
				" volcano\n" +
				" earthquake\n" +
				" limestone\n" +
				" sandstone\n" +
				" bedrock\n" +
				" stalactite\n" +
				" stalagmite\n" +
				" cavern\n" +
				" grotto\n" +
				" crevice\n" +
				" shoreline\n" +
				" coastline\n" +
				" headland\n" +
				" offshore\n" +
				" seafloor\n" +
				" submarine\n" +
				" underwater\n" +
				" seagrass\n" +
				" coral\n" +
				" jellyfish\n" +
				" seahorse\n" +
				" sailfish\n" +
				" swordfish\n" +
				" blowfish\n" +
				" goldfish\n" +
				" starfish\n" +
				" crayfish\n" +
				" lobster\n" +
				" barnacle\n" +
				" seabird\n" +
				" pelican\n" +
				" albatross\n" +
				" seagull\n" +
				" cormorant\n" +
				" puffin\n" +
				" osprey\n" +
				" heron\n" +
				" egret\n" +
				" flamingo\n" +
				" stork\n" +
				" kingfisher\n" +
				" swallow\n" +
				" sparrow\n" +
				" finch\n" +
				" warbler\n" +
				" thrush\n" +
				" robin\n" +
				" bluebird\n" +
				" woodpecker\n" +
				" chickadee\n" +
				" nuthatch\n" +
				" starling\n" +
				" magpie\n" +
				" raven\n" +
				" jackdaw\n" +
				" buzzard\n" +
				" harrier\n" +
				" kestrel\n" +
				" merlin\n" +
				" peregrine\n" +
				" falcon\n" +
				" goshawk\n" +
				" sparrowhawk\n" +
				" nighthawk\n" +
				" whippoorwill\n" +
				" mockingbird\n" +
				" nightingale\n" +
				" lark\n" +
				" skylark\n" +
				" curlew\n" +
				" sandpiper\n" +
				" snipe\n" +
				" avocet\n" +
				" lapwing\n" +
				" plover\n" +
				" wagtail\n" +
				" pipit\n" +
				" bunting\n" +
				" linnet\n" +
				" goldfinch\n" +
				" chaffinch\n" +
				" bullfinch\n" +
				" crossbill\n" +
				" redpoll\n" +
				" siskin\n" +
				" greenfinch\n" +
				" hawfinch\n" +
				" treecreeper\n" +
				" dipper\n" +
				" waxwing\n" +
				" redstart\n" +
				" stonechat\n" +
				" wheatear\n" +
				" flycatcher\n" +
				" petrel\n" +
				" shearwater\n" +
				" gannet\n" +
				" booby\n" +
				" frigatebird\n" +
				" tropicbird\n" +
				" skimmer\n" +
				" tern\n" +
				" noddy\n" +
				" skua\n" +
				" jaeger\n" +
				" phalarope\n" +
				" turnstone\n" +
				" dunlin\n" +
				" knot\n" +
				" redshank\n" +
				" greenshank\n" +
				" godwit\n" +
				" whimbrel\n" +
				" oystercatcher\n" +
				" stilts\n" +
				" ibis\n" +
				" spoonbill\n" +
				" bittern\n" +
				" grebe\n" +
				" coot\n" +
				" moorhen\n" +
				" gallinule\n" +
				" rail\n" +
				" corncrake\n" +
				" bustard\n" +
				" crane\n" +
				" cassowary\n" +
				" ostrich\n" +
				" rhea\n" +
				" emu\n" +
				" kiwi\n" +
				" toucan\n" +
				" parrot\n" +
				" macaw\n" +
				" cockatoo\n" +
				" cockatiel\n" +
				" lorikeet\n" +
				" lovebird\n" +
				" budgerigar\n" +
				" pigeon\n" +
				" dove\n" +
				" cuckoo\n" +
				" roadrunner\n" +
				" kingfisher\n" +
				" bee-eater\n" +
				" roller\n" +
				" hoopoe\n" +
				" hornbill\n" +
				" barbet\n" +
				" woodpecker\n" +
				" wryneck\n" +
				" piculet\n" +
				" jacamar\n" +
				" puffbird\n" +
				" manakin\n" +
				" cotinga\n" +
				" tanager\n" +
				" cardinal\n" +
				" grosbeak\n" +
				" bunting\n" +
				" saltator\n" +
				" thrasher\n" +
				" catbird\n" +
				" wren\n" +
				" dipper\n" +
				" starling\n" +
				" myna\n" +
				" oxpecker\n" +
				" sunbird\n" +
				" honeyeater\n" +
				" flowerpecker\n" +
				" white-eye\n" +
				" babbler\n" +
				" scimitar\n" +
				" fulvetta\n" +
				" liocichla\n" +
				" shrike\n" +
				" bushshrike\n" +
				" helmet-shrike\n" +
				" vanga\n" +
				" woodshrike\n" +
				" oriole\n" +
				" figbird\n" +
				" drongo\n" +
				" monarch\n" +
				" fantail\n" +
				" paradise-flycatcher\n" +
				" silktail\n" +
				" whistler\n" +
				" shrike-thrush\n" +
				" pitohui\n" +
				" ifrit\n" +
				" satinbird\n" +
				" melampita\n" +
				" rockfowl\n" +
				" rockjumper\n" +
				" rail-babbler\n" +
				" sapayoa\n" +
				" broadbill\n" +
				" pitta\n" +
				" asity\n" +
				" scrub-bird\n" +
				" lyrebird\n" +
				" riflebird\n" +
				" sicklebill\n" +
				" lophorina\n" +
				" parotia\n" +
				" astrapia\n" +
				" seleucidis\n" +
				" paradigalla\n" +
				" epimachus\n" +
				" ptiloris\n" +
				" diphyllodes\n" +
				" cicinnurus\n" +
				" pteridophora\n" +
				" semioptera\n" +
				" tanysiptera\n" +
				" melidectes\n" +
				" melanocharis\n" +
				" rhamphocharis\n" +
				" oedistoma\n" +
				" toxorhamphus\n" +
				" eulacestoma\n" +
				" orthonyx\n" +
				" cinclosoma\n" +
				" psophodes\n" +
				" pomatostomus\n" +
				" daphoenositta\n" +
				" monkey\n" +
				" climacteris\n" +
				" cormobates\n" +
				" acanthisitta\n" +
				" xenicus\n" +
				" traversia\n" +
				" pachycare\n" +
				" crateroscelis\n" +
				" sericornis\n" +
				" gerygone\n" +
				" aphelocephala\n" +
				" smicrornis\n" +
				" chthonicola\n" +
				" pycnoptilus\n" +
				" origma\n" +
				" hylacola\n" +
				" calamanthus\n" +
				" acanthiza\n" +
				" pyrrholaemus\n" +
				" stipiturus\n" +
				" amytornis\n" +
				" dasiornis\n" +
				" dasyornis\n" +
				" ephthianura\n" +
				" ashbyia\n" +
				" epthianura\n" +
				" bowdleria\n" +
				" megalurus\n" +
				" schoenicola\n" +
				" bradypterus\n" +
				" locustella\n" +
				" acrocephalus\n" +
				" iduna\n" +
				" hippolais\n" +
				" sylvia\n" +
				" curruca\n" +
				" phylloscopus\n" +
				" seicercus\n" +
				" tickellia\n" +
				" abroscopus\n" +
				" cryptillas\n" +
				" graueria\n" +
				" melocichla\n" +
				" sphenoeacus\n" +
				" artisornis\n" +
				" bathmocercus\n" +
				" camaroptera\n" +
				" calamonastes\n" +
				" euryptila\n" +
				" oreophilais\n" +
				" phragmacia\n" +
				" cisticola\n" +
				" prinia\n" +
				" apalis\n" +
				" oreolais\n" +
				" schistolais\n" +
				" spiloptila\n" +
				" micromacronus\n" +
				" macronus\n" +
				" stachyris\n" +
				" cyanoderma\n" +
				" mixornis\n" +
				" dumetia\n" +
				" rhopocichla\n" +
				" napothera\n" +
				" kenopia\n" +
				" ptilocichla\n" +
				" spelaeornis\n" +
				" sphenocichla\n" +
				" rimator\n" +
				" turdoides\n" +
				" chatarrhaea\n" +
				" malacocircus\n" +
				" argya\n" +
				" acanthoptila\n" +
				" horornis\n" +
				" cettia\n" +
				" niltava\n" +
				" cyornis\n" +
				" ficedula\n" +
				" muscicapa\n" +
				" melaenornis\n" +
				" bradornis\n" +
				" fraseria\n" +
				" agricola\n" +
				" sigelus\n" +
				" dioptrornis\n" +
				" empidornis\n" +
				" rhinomyias\n" +
				" myioparus\n" +
				" humblotia\n" +
				" horizorhinus\n" +
				" cossypha\n" +
				" sheppardia\n" +
				" xenocopsychus\n" +
				" cichladusa\n" +
				" trichixos\n" +
				" stizorhina\n" +
				" stiphrornis\n" +
				" neocossyphus\n" +
				" myadestes\n" +
				" sialia\n" +
				" grandala\n" +
				" cochoa\n" +
				" monticola\n" +
				" pseudocossyphus\n" +
				" myophonus\n" +
				" zoothera\n" +
				" catharus\n" +
				" hylocichla\n" +
				" turdus\n" +
				" nesocichla\n" +
				" cichlherminia\n" +
				" platycichla\n" +
				" ridgwayia\n" +
				" ixoreus\n" +
				" chlamydochaera\n" +
				" psarophagia\n" +
				" alethe\n" +
				" pseudalethe\n" +
				" kupeornis\n" +
				" modulatrix\n" +
				" arcanator\n" +
				" heinrichia\n" +
				" stizorhina\n" +
				" malacocincla\n" +
				" pellorneum\n" +
				" leonardina\n" +
				" trichastoma\n" +
				" robsonius\n" +
				" ptilocichla\n" +
				" malacopteron\n" +
				" malacocopteron\n" +
				" graminicola\n" +
				" chaetornis\n" +
				" laticilla\n" +
				" brownbill\n" +
				" grassbird\n" +
				" spinetail\n" +
				" thornbill\n" +
				" weebill\n" +
				" pardalote\n" +
				" scrubwren\n" +
				" bristlebird\n" +
				" fieldwren\n" +
				" hylacola\n" +
				" rockwarbler\n" +
				" pilotbird\n" +
				" fernwren\n" +
				" heathwren\n" +
				" redthroat\n" +
				" whiteface\n" +
				" quailfinch\n" +
				" cordonbleu\n" +
				" pytilia\n" +
				" firefinch\n" +
				" waxbill\n" +
				" munia\n" +
				" mannikin\n" +
				" silverbill\n" +
				" sparrow\n" +
				" weaver\n" +
				" fody\n" +
				" bishop\n" +
				" widowbird\n" +
				" indigobird\n" +
				" whydah\n" +
				" bunting\n" +
				" longspur\n" +
				" snowbird\n" +
				" junco\n" +
				" towhee\n" +
				" sparrow\n" +
				" grosbeak\n" +
				" cardinal\n" +
				" chat\n" +
				" warbler\n" +
				" parula\n" +
				" redstart\n" +
				" ovenbird\n" +
				" waterthrush\n" +
				" yellowthroat\n" +
				" chat\n" +
				" oriole\n" +
				" blackbird\n" +
				" meadowlark\n" +
				" grackle\n" +
				" cowbird\n" +
				" bobolink\n" +
				" jay\n" +
				" crow\n" +
				" rook\n" +
				" chough\n" +
				" jackdaw\n" +
				" nutcracker\n" +
				" magpie\n" +
				" treepie\n" +
				" ground-jay\n" +
				" raven\n" +
				" oxpecker\n" +
				" starling\n" +
				" myna\n" +
				" crested\n" +
				" common\n" +
				" hill\n" +
				" jungle\n" +
				" golden\n" +
				" vinous\n" +
				" pale\n" +
				" white\n" +
				" finch\n" +
				" rufous\n" +
				" superb");
		Randomizer randomizer = new Randomizer("database", 26);
		randomizer.generateRandomWords();
		randomizer.encryptLetters();
		Encryptor encryptor = new Encryptor(randomizer, database);
		String password = "rinatbik";
		System.out.println(randomizer.getKey());
		System.out.println("Original password: " + password + " \nEncrypted password: " + encryptor.encrypt(password));
		SpringApplication.run(RandomizerApplication.class, args);
	}

}
